version: '3'
services:
  db:
    image: mysql:8.0.18
    environment:
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
      - ./logs:/var/log/mysql

  test-db:
    image: mysql:8.0.18
    environment:
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      MYSQL_DATABASE: app_test
    ports:
      - '3307:3306' # ローカルPCから接続するために設定

  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle 
      - node-modules:/app/node_modules

    ports:
      - "3003:3000"
    depends_on:
      - db

volumes:
  bundle:
  node-modules: